/usr/local/lib/python3.6/dist-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2020-01-13 13:36:01,466: INFO/MainProcess] Connected to redis://127.0.0.1:6379/0
[2020-01-13 13:36:01,488: INFO/MainProcess] mingle: searching for neighbors
[2020-01-13 13:36:02,531: INFO/MainProcess] mingle: all alone
[2020-01-13 13:36:02,560: INFO/MainProcess] celery@7fddbfd9c0ed ready.
[2020-01-13 13:36:27,771: INFO/MainProcess] Received task: main.task_executor[ef391327-f5fa-43fe-b0d1-67fe2d53cd1d]  
/usr/local/lib/python3.6/dist-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2020-01-13 13:36:27,791: INFO/ForkPoolWorker-2] Task main.task_executor[ef391327-f5fa-43fe-b0d1-67fe2d53cd1d] succeeded in 0.01123379999626195s: 30
/usr/local/lib/python3.6/dist-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2020-01-14 05:28:47,087: INFO/MainProcess] Connected to redis://127.0.0.1:6379/0
[2020-01-14 05:28:47,103: INFO/MainProcess] mingle: searching for neighbors
[2020-01-14 05:28:48,141: INFO/MainProcess] mingle: all alone
[2020-01-14 05:28:48,173: INFO/MainProcess] celery@8223a75931fb ready.
[2020-01-14 05:34:18,678: INFO/MainProcess] Received task: main.task_executor[7fac65b1-237f-41da-8ef2-afff163d9f93]  
/usr/local/lib/python3.6/dist-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2020-01-14 05:34:18,706: INFO/ForkPoolWorker-2] Task main.task_executor[7fac65b1-237f-41da-8ef2-afff163d9f93] succeeded in 0.01573550000000523s: 30
/usr/local/lib/python3.6/dist-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2020-01-14 05:42:33,631: INFO/MainProcess] Connected to redis://127.0.0.1:6379/0
[2020-01-14 05:42:33,649: INFO/MainProcess] mingle: searching for neighbors
[2020-01-14 05:42:34,692: INFO/MainProcess] mingle: all alone
[2020-01-14 05:42:34,718: INFO/MainProcess] celery@1a2436663f13 ready.
/usr/local/lib/python3.6/dist-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2020-01-14 06:20:32,943: INFO/MainProcess] Connected to redis://127.0.0.1:6379/0
[2020-01-14 06:20:32,974: INFO/MainProcess] mingle: searching for neighbors
[2020-01-14 06:20:34,066: INFO/MainProcess] mingle: all alone
[2020-01-14 06:20:34,115: INFO/MainProcess] celery@68165ed80a73 ready.
[2020-01-14 06:23:56,103: INFO/MainProcess] Received task: main.task_executor[8a7cc41d-5c82-43eb-89be-ef70ea200e20]  
/usr/local/lib/python3.6/dist-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2020-01-14 06:23:56,120: INFO/ForkPoolWorker-2] Task main.task_executor[8a7cc41d-5c82-43eb-89be-ef70ea200e20] succeeded in 0.01041370000001507s: 30
[2020-01-14 07:27:17,099: INFO/MainProcess] Received task: main.task_executor[5449a646-45cb-44c2-947c-e2445a1386e4]  
[2020-01-14 07:27:17,114: ERROR/ForkPoolWorker-2] Task main.task_executor[5449a646-45cb-44c2-947c-e2445a1386e4] raised unexpected: TypeError("task_executor() got an unexpected keyword argument 'tasktype'",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: task_executor() got an unexpected keyword argument 'tasktype'

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@68165ed80a73 v4.4.0 (cliffs)
--- ***** ----- 
-- ******* ---- Linux-4.9.184-linuxkit-x86_64-with-Ubuntu-18.04-bionic 2020-01-14 06:20:32
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         main:0x7fe47be98748
- ** ---------- .> transport:   redis://127.0.0.1:6379/0
- ** ---------- .> results:     redis://127.0.0.1:6379/0
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . main.task_executor

/usr/local/lib/python3.6/dist-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2020-01-14 07:29:32,650: INFO/MainProcess] Connected to redis://127.0.0.1:6379/0
[2020-01-14 07:29:32,666: INFO/MainProcess] mingle: searching for neighbors
[2020-01-14 07:29:33,701: INFO/MainProcess] mingle: all alone
[2020-01-14 07:29:33,725: INFO/MainProcess] celery@68165ed80a73 ready.
[2020-01-14 07:29:42,649: INFO/MainProcess] Received task: main.task_executor[a203f759-9736-4c2b-b53d-e84ece57975e]  
/usr/local/lib/python3.6/dist-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2020-01-14 07:29:42,656: WARNING/ForkPoolWorker-2] ml_clf
[2020-01-14 07:29:42,670: INFO/ForkPoolWorker-2] Task main.task_executor[a203f759-9736-4c2b-b53d-e84ece57975e] succeeded in 0.013957800000753195s: None
