/usr/local/lib/python3.6/dist-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2020-01-13 13:36:01,466: INFO/MainProcess] Connected to redis://127.0.0.1:6379/0
[2020-01-13 13:36:01,488: INFO/MainProcess] mingle: searching for neighbors
[2020-01-13 13:36:02,531: INFO/MainProcess] mingle: all alone
[2020-01-13 13:36:02,560: INFO/MainProcess] celery@7fddbfd9c0ed ready.
[2020-01-13 13:36:27,771: INFO/MainProcess] Received task: main.task_executor[ef391327-f5fa-43fe-b0d1-67fe2d53cd1d]  
/usr/local/lib/python3.6/dist-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2020-01-13 13:36:27,791: INFO/ForkPoolWorker-2] Task main.task_executor[ef391327-f5fa-43fe-b0d1-67fe2d53cd1d] succeeded in 0.01123379999626195s: 30
